### ISSUE TITLE
Allow vocabulary-only custom vocabularies

### ISSUE THREAD

**Issue by Spayralbe** [thehyve/delphyne#100]
A call to `load_custom_vocabularies` currently doesn't allow adding or updating vocabularies that consist of only a record in the vocabulary table (no linked concept_ids).

https://github.com/thehyve/delphyne/blob/37afdf7496577214749eccccdaa68c6eeb2d3c50/src/delphyne/model/custom_vocab/custom_vocab_loader.py#L68-L70

For STCM files it is however rather common to only need a custom source_vocabulary_id value, but no linked source_concept_ids. It would therefore be useful to allow this scenario and load only the vocabulary_id records.

**Comment by alepev** [comment]
oops, I didn't realize how this would affect the STCM vocabularies loading. I can simply remove this check

**Comment by Spayralbe** [comment]
> oops, I didn't realize how this would affect the STCM vocabularies loading. I can simply remove this check

Yes I think it's as simple as that 👍
