### ISSUE TITLE
Fix typo in COST table v5.3.1

### ISSUE THREAD

**Issue by alepev** [thehyve/delphyne#108]
An attribute of Cost table v5.3.1 is currently spelled `reveue_code_source_value` following the official [CDM Postgres DDL](https://github.com/OHDSI/CommonDataModel/blob/ca1b2376c48c6d72aa581a82ceb5b008ffdc218e/PostgreSQL/OMOP%20CDM%20postgresql%20ddl.txt#L653). 
However [here](https://github.com/OHDSI/CdmDdlBase/blob/master/inst/csv/OMOP_CDMv5.3.1_Field_Level.csv) this has been officially corrected to be `revenue_code_source_value`. Given this is the way it has been implemented in the Data Quality Dashboard, we assume we shouldn't be concerned about the code change breaking OHDSI data quality tools. Update to the the correct spelling (which looks a lot better).

**Comment by alepev** [comment]
@MaximMoinat just to be sure, can you confirm the new spelling is what the DQD checks for? I wonder how many errors users get because of the mismatch between the official DDL and what the DQD expects 🙈

**Comment by MaximMoinat** [comment]
Good point, and yes the DQD expects the correct spelling of revenue

https://github.com/OHDSI/DataQualityDashboard/blob/master/inst/csv/OMOP_CDMv5.3.1_Field_Level.csv#L277

**Comment by MaximMoinat** [comment]
By the way, the typo has been corrected in the v5.3.1_fixes branch.

https://github.com/OHDSI/CommonDataModel/blob/v5.3.1_fixes/PostgreSQL/OMOP%20CDM%20postgresql%20v5_3_1%20ddl.sql

I will raise an issue on the CDM repo that the 5.3.1 tag should be updated.

**Comment by alepev** [comment]
Thanks, and good there was already a fix, I was really wondering how it could be that inconsistent!

**Comment by alepev** [comment]
@Spayralbe I was wondering if it could be worth checking for other fixes in the `v5.3.1_fixes` branch mentioned above, and update our model accordingly.. new issue?

**Comment by Spayralbe** [comment]
> @Spayralbe I was wondering if it could be worth checking for other fixes in the `v5.3.1_fixes` branch mentioned above, and update our model accordingly.. new issue?

Yes, would be wise to check. New issue sounds good 👍

**Comment by alepev** [comment]
Followed up in #112
