### ISSUE TITLE
Check `v5.3.1_fixes` branch of official CDM repo

### ISSUE THREAD

**Issue by alepev** [thehyve/delphyne#112]
Compare our current CDM v5.3.1 implementation to the `v5.3.1_fixes` branch in the official CDM repo and apply any changes: https://github.com/OHDSI/CommonDataModel/tree/v5.3.1_fixes/PostgreSQL

**Comment by MaximMoinat** [comment]
I think this issue describes all the fixes made in that branch: https://github.com/OHDSI/CommonDataModel/issues/297
