### ISSUE TITLE
Data type of keys should be BigInteger

### ISSUE THREAD

**Issue by MaximMoinat** [thehyve/delphyne#117]
**Describe the bug**
Data type is integer, causes issues for large numbers. 

**Expected behavior**
According to the OMOP CDM documentation, most integer keys are of type BigInteger

**Comment by Spayralbe** [comment]
We currently use the data types as defined in the official CDM releases, for which the keys are Ints in v5.3.1 and Bigints in v6.0.0. @MaximMoinat Would you be in favor of making those Bigints by default for v5.3.1 as well?

**Comment by MaximMoinat** [comment]
You are absolutely right. In that case, we stick with the definition.

For UKB we need BigInts for visit occurrences. And customisation of the data model is perfectly supported by delphyne.

@Spayralbe I am closing this issue, no action needed.
