### ISSUE TITLE
Document STCM usage

### ISSUE THREAD

**Issue by alepev** [thehyve/delphyne#123]
Depends on https://github.com/thehyve/omop-etl-wrapper/issues/41

**Comment by alepev** [comment]
Note: if putting this under Semantic Mapping, make sure it is visible in the left menu in expanded view

**Comment by alepev** [comment]
@Spayralbe apparently if I change the vocabulary names in `stcm_versions.tsv` (say the custom vocabularies I was referencing have been deleted and I want to use different ones), the old vocabularies are not automatically removed from the STCM_VERSION table in the database. Once the constraints are re-applied, I get a FK constraints error because the deleted vocabularies are still being referenced. Shall I make an issue to add a STCM_VERSION cleanup? Or is there a reason stcm behaves like this?

**Comment by alepev** [comment]
Another thing: `stcm_loader` seems to read any file in the `source_to_concept_map` folder irrespectively of the suffix (doesn't matter if it ends in `_stcm` or not). I discovered when trying to exclude some incomplete stcm files by removing the suffix.. Also a reason for this, or shall I make an issue?

**Comment by Spayralbe** [comment]
> @Spayralbe apparently if I change the vocabulary names in `stcm_versions.tsv` (say the custom vocabularies I was referencing have been deleted and I want to use different ones), the old vocabularies are not automatically removed from the STCM_VERSION table in the database. Once the constraints are re-applied, I get a FK constraints error because the deleted vocabularies are still being referenced. Shall I make an issue to add a STCM_VERSION cleanup? Or is there a reason stcm behaves like this?

At time of implementing I wasn't quite sure whether automatically deleting vocabularies that are not referenced (anymore) in the STCM version file was a good idea, so currently they are ignored. However, I think it would be good to make the behavior consistent with the custom vocab loader, so it's fine with me if dropping those becomes the default behavior.

**Comment by Spayralbe** [comment]
> Another thing: `stcm_loader` seems to read any file in the `source_to_concept_map` folder irrespectively of the suffix (doesn't matter if it ends in `_stcm` or not). I discovered when trying to exclude some incomplete stcm files by removing the suffix.. Also a reason for this, or shall I make an issue?
> 
> At the moment, it is implemented like this:
> 
> ```python
> def _get_stcm_files() -> Set[Path]:
>     files = get_all_files_in_dir(STCM_DIR)
>     return {f for f in files if not f.name == STCM_VERSION_FILE.name}
> ```

I think the current behavior doesn't have to be changed. Either you indicate a file belongs to a specific source vocabulary with the <VOCAB_ID>_stcm notation, or it will be always be parsed as a regular STCM file.
If a file shouldn't be used, it shouldn't be in the source_to_concept_map folder.

**Comment by alepev** [comment]
Thanks! :)

**Comment by alepev** [comment]
Created issue #161

**Comment by alepev** [comment]
> > Another thing: `stcm_loader` seems to read any file in the `source_to_concept_map` folder irrespectively of the suffix (doesn't matter if it ends in `_stcm` or not). I discovered when trying to exclude some incomplete stcm files by removing the suffix.. Also a reason for this, or shall I make an issue?
> > At the moment, it is implemented like this:
> > ```python
> > def _get_stcm_files() -> Set[Path]:
> >     files = get_all_files_in_dir(STCM_DIR)
> >     return {f for f in files if not f.name == STCM_VERSION_FILE.name}
> > ```
> 
> I think the current behavior doesn't have to be changed. Either you indicate a file belongs to a specific source vocabulary with the <VOCAB_ID>_stcm notation, or it will be always be parsed as a regular STCM file.
> If a file shouldn't be used, it shouldn't be in the source_to_concept_map folder.

As for this one, I am quite strict with what is allowed in the custom_vocabulary folder.. but it's true that there we have different file suffixes for different tables in that case, so we need the extra checks. We can leave it as is for STCM for now.
