### ISSUE TITLE
Create combined STCM and custom vocab method in VocabManager

### ISSUE THREAD

**Issue by Spayralbe** [thehyve/delphyne#128]
Currently, when a new version of a custom vocabulary is provided, the records of that vocabulary are first deleted and then the new version is loaded. This breaks FK constraints when the vocabulary was already used by an STCM mapping. To make it work, you therefore need to drop the STCM records manually first.

~~It would be more convenient if these STCM FKs were dropped in case vocabularies need to be reloaded that are used by the STCM tables. They should then be reapplied afterwards.~~

**Comment by Spayralbe** [comment]
One thing to note here is that it will only resolve cases where the newly loaded custom vocabularies are compatible with the already loaded STCMs. If both updated custom vocabularies and updated STCMs are provided at the same time, it could still break, even though the newly provided ones are compatible with each other 🤔

**Comment by alepev** [comment]
Wait, why would it break if both are updated? If the new vocabulary version is loaded first, then a new stcm version that refers to that vocabulary is loaded, shouldn't that work fine?

**Comment by alepev** [comment]
Anyway, combining seems a good idea, otherwise the user could very easily mix up the execution order of the steps and get into trouble. Having a single interface to handle this seems safer.

**Comment by Spayralbe** [comment]
> Wait, why would it break if both are updated? If the new vocabulary version is loaded first, then a new stcm version that refers to that vocabulary is loaded, shouldn't that work fine?

If applied like described in the issue description that won't work. Because constraints would be re-applied after the loading of the custom vocabs, but STCM would still contain the old versions at that point.

**Comment by alepev** [comment]
I see, sorry I also got confused about the timing of the constraints removal / re-application! I thought re-applying them would be the last step already, indeed a method that ensures that makes perfectly sense
