### ISSUE TITLE
Document use of different transformation wrappers

### ISSUE THREAD

**Issue by alepev** [thehyve/delphyne#145]
e.g. `execute_transformation` vs `execute_batch_transformation`, and examples of how transformation itself should be adapted for each

**Comment by MaximMoinat** [comment]
Happy to help out here. If you can give me a bit more pointers where this documentation should go, then feel free to assign it to me :)

**Comment by alepev** [comment]
@MaximMoinat it looks like we already have a stub [here](https://github.com/thehyve/delphyne/blob/master/docs/transformations.rst), you can check other rst files for formatting examples (still have to write one myself)
