### ISSUE TITLE
Add execute_transformation option for SQLAlchemy Query

### ISSUE THREAD

**Issue by Spayralbe** [thehyve/delphyne#153]
Currently there are options for executing queries via the ORM, or by using raw SQL queries. It would be useful to have a third option using the SQLAlchemy Query definition. That way you will have the same performance as raw SQL, but you can still make the queries dialect-agnostic.

- [x] Add the execution method to wrapper
- [x] Add collection method for transformation metadata

**Comment by alepev** [comment]
See implementation here: https://github.com/thehyve/ohdsi-etl-v5-to-v6/blob/369a2aaa408d0b74650bdedf0a0ee743ded0c244/src/main/python/model/base_wrapper.py#L72
