### ISSUE TITLE
Update STCM table constraints

### ISSUE THREAD

**Issue by alepev** [thehyve/delphyne#158]
PKs on 2 columns missing. See here: https://github.com/OHDSI/CommonDataModel/blob/35d53c9f5a950aa7116f281b1cd0ad37902d2456/PostgreSQL/OMOP%20CDM%20postgresql%20pk%20indexes.txt#L76

**Comment by Spayralbe** [comment]
So what part is missing exactly? Isn't the PK on the same 4 columns?

**Comment by alepev** [comment]
You are right and I'm blind. I had a look again at the offending stcm tables in the other project, indeed ALL of the PKs are duplicated - not pointing to different target concept_ids as I thought -__- that's not multiple mappings, it's redundancy..  @MaximMoinat FYI
