### ISSUE TITLE
Set up documentation

### ISSUE THREAD

**Issue by alepev** [thehyve/delphyne#28]
- [x] decide on Read the Docs, Just the Docs, other..
- [x] automatically generate basic documentation (public methods)

**Comment by MaximMoinat** [comment]
@Spayralbe Do you have a preference for ReadTheDocs or JustTheDocs? (and why?)

**Comment by Spayralbe** [comment]
@MaximMoinat JustTheDocs is indeed simpler, but I think would be useful to have sphinx autodoc to generate documentation directly from the docstrings. The more extensive features of rst might also come in handy.

ReadTheDocs will allow you to automatically deploy your documentation and can host multiple versions of the documentation, each tied to a specific release.

**Comment by MaximMoinat** [comment]
Agreed! That will make our lives a lot easier.
