### ISSUE TITLE
Custom vocabulary file recognition

### ISSUE THREAD

**Issue by Spayralbe** [thehyve/delphyne#57]
Currently custom vocabulary files can be indicated to belong to a specific vocabulary_id by by including it into the filename, e.g. CUSTOMVOCAB1_concept.tsv. This information should be used to skip the file if no new version of this particular vocabulary is detected, instead of checking each individual record's vocabulary_id.

**Comment by alepev** [comment]
@Spayralbe For `StcmLoader`, can we consider this covered by this and related pieces of code?
https://github.com/thehyve/omop-etl-wrapper/blob/e57db47ccfce66c09f25c5ec5d961cd067e66597/src/omop_etl_wrapper/model/stcm/stcm_loader.py#L103-L109
I will try to apply this to `CustomVocabLoader`.. I'll make it part of the next PR

**Comment by Spayralbe** [comment]
One part that may need to be revised is extracting the vocabulary_id from the file name. See [`_get_stcm_file_vocab_id`](https://github.com/thehyve/omop-etl-wrapper/blob/febab622dd0dbe5d01e00bacd6272c91e8a6f5ee/src/omop_etl_wrapper/model/stcm/stcm_loader.py#L114).

**Comment by alepev** [comment]
This is now handled by `get_file_prefix()` in `utils/io.py`, a function introduced in #81. If the change is sufficient, we can link the issue to that PR.

**Comment by alepev** [comment]
@Spayralbe also pretty sure this one was already satisfied, I'm closing it
