### ISSUE TITLE
Investigate how to capture deletions and updates

### ISSUE THREAD

**Issue by alepev** [thehyve/delphyne#82]
Currently only insertions are reported in `etl_stats`. How to get counts for updates and deletions when using session.query? Can we think of workarounds?

**Comment by Spayralbe** [comment]
All operations on the instance level are already captured by the `before_flush` listener, but bulk delete/update via session.query are missed. I propose we add the `after_bulk_delete` and `after_bulk_update` event listeners to capture this information (if the session is linked to an `EtlTransformation` instance).
